language: ruby
before_install:
  - gem install -v '1.17.3' bundler
install: bundle _1.17.3_ install
bundler_args: --jobs 3 --retry 3 --without benchmark
os:
  - linux
  - osx
rvm:
  - 2.1.10
  - 2.0.0
  - 1.9.3
matrix:
  exclude:
    - rvm: 2.0.0
      os: osx
    - rvm: 1.9.3
      os: osx
  include:
    - rvm: 2.0.0
      os: osx
      osx_image: xcode7.3
    - rvm: 1.9.3
      os: osx
      osx_image: xcode7.3
